import { useState } from 'react';
import agentRuntime from '@services/agentRuntime';
import authService from '@services/authService';

const Checklist = () => {
  const [query, setQuery] = useState('');
  const [loading, setLoading] = useState(false);
  const [results, setResults] = useState(null);
  const [error, setError] = useState('');

  const parseQuery = (q) => {
    const lower = q.toLowerCase();
    const customerTypes = [];
    if (lower.includes('naivas')) customerTypes.push('NAIVAS');
    if (lower.includes('khetia')) customerTypes.push('KHETIA');
    if (lower.includes('quickmart')) customerTypes.push('QUICKMART');
    if (lower.includes('chandarana')) customerTypes.push('CHANDARANA');
    if (lower.includes('cleanshelf')) customerTypes.push('CLEANSHELF');
    if (lower.includes('jazaribu')) customerTypes.push('JAZARIBU');
    if (lower.includes('majid') || lower.includes('carrefour')) customerTypes.push('MAJID');
    if (customerTypes.length === 0) {
      customerTypes.push('NAIVAS', 'KHETIA', 'QUICKMART', 'CHANDARANA', 'CLEANSHELF', 'JAZARIBU', 'MAJID');
    }

    const knownBranches = authService.getUserBranches() || [];
    const branches = [];
    for (const b of knownBranches) {
      if (lower.includes(b.toLowerCase())) branches.push(b);
    }

    let date = new Date();
    date.setDate(date.getDate() + 1);
    if (lower.includes('today')) date = new Date();
    else if (lower.includes('friday')) { while (date.getDay() !== 5) date.setDate(date.getDate() + 1); }

    return { customerTypes, branches, date: date.toISOString().split('T')[0] };
  };

  const handleGenerate = async () => {
    if (!query.trim()) return;
    if (!agentRuntime.isReady()) {
      setError('Agent data is still loading. Please wait.');
      return;
    }

    setLoading(true);
    setError('');
    setResults(null);

    try {
      const { customerTypes, branches, date } = parseQuery(query);
      const allBranches = branches.length > 0 ? branches : (authService.getUserBranches() || []);

      const data = await agentRuntime.generateChecklist(customerTypes, allBranches, date);
      setResults({ data, customerTypes, date, query });
    } catch (e) {
      setError(e.message);
    } finally {
      setLoading(false);
    }
  };

  const exportCSV = () => {
    if (!results) return;
    const rows = [['Customer', 'Branch', 'Route', 'LPO', 'Amount', 'Status']];
    results.data.forEach(r => {
      rows.push([r.customer, r.branch, r.route, r.lpo, r.amount.toString(), r.status]);
    });
    const csv = rows.map(r => r.map(c => `"${c}"`).join(',')).join('\n');
    const blob = new Blob([csv], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `checklist-${new Date().toISOString().split('T')[0]}.csv`;
    a.click();
  };

  const shareWhatsApp = () => {
    if (!results) return;
    const placed = results.data.filter(r => r.placed);
    const missing = results.data.filter(r => !r.placed);
    let text = `CHECKLIST — ${results.customerTypes.join('/')} — ${results.date}\n`;
    text += `═══════════════════════════\n`;
    text += `RECEIVED (${placed.length}/${results.data.length})\n`;
    placed.slice(0, 10).forEach(r => {
      text += `  ${r.customer} — ${r.lpo} — Ksh ${r.amount.toLocaleString()}\n`;
    });
    if (missing.length > 0) {
      text += `\nNOT RECEIVED (${missing.length})\n`;
      missing.slice(0, 10).forEach(r => {
        text += `  ${r.customer} — ${r.branch}\n`;
      });
    }
    text += `\n═══════════════════════════\n`;
    text += `Generated by CT226`;
    window.open(`https://web.whatsapp.com/send?text=${encodeURIComponent(text)}`, '_blank');
  };

  return (
    <div className="checklist-tab">
      <h2>CHECKLIST</h2>
      <p className="checklist-intro">Hello! What checklist do you need?</p>
      
      <div className="checklist-input-row">
        <input
          type="text"
          value={query}
          onChange={e => setQuery(e.target.value)}
          onKeyDown={e => e.key === 'Enter' && handleGenerate()}
          placeholder="e.g. Jazaribu checklist for Kitengela and Thika"
          disabled={loading}
        />
        <button onClick={handleGenerate} disabled={loading || !query.trim()}>
          {loading ? '.' : 'Generate'}
        </button>
      </div>

      {error && <div className="error-message">Error: {error}</div>}

      {results && (
        <div className="checklist-results">
          <div className="checklist-summary">
            {results.customerTypes.join('/')} — {results.date} — {results.data.length} outlets
          </div>
          
          <div className="checklist-actions">
            <button onClick={exportCSV}>Export CSV</button>
            <button onClick={shareWhatsApp}>Share via WhatsApp</button>
          </div>

          <div className="checklist-list">
            {results.data.map((r, i) => (
              <div key={i} className={`checklist-item ${r.placed ? 'received' : 'not-received'}`}>
                <span className="checklist-status">{r.placed ? '[+]' : '[-]'}</span>
                <span className="checklist-customer">{r.customer}</span>
                <span className="checklist-branch">{r.branch}</span>
                <span className="checklist-lpo">{r.lpo}</span>
                {r.placed && <span className="checklist-amount">Ksh {r.amount.toLocaleString()}</span>}
                <span className="checklist-status-text">{r.status}</span>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
};

export default Checklist;
